modLoader = "javafml"
loaderVersion = "[@LOADER_MAJOR@,)"
issueTrackerURL = "https://github.com/Luke100000/ImmersiveParticles/issues"
license = "GPL-3.0-only"

[[mods]]
modId = "immersive_particles"
version = "${version}"
displayName = "Immersive Particles"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/immersive-particles"
authors = "Luke100000"
description = "Client side, performant particles to give your environment some life!"
logoFile = "icon.png"

[[dependencies.immersive_particles]]
modId = "minecraft"
mandatory = true
versionRange = "[@MINECRAFT_VERSION@,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.immersive_particles]]
modId = "forge"
mandatory = true
versionRange = "[@LOADER_MAJOR@,)"
ordering = "NONE"
side = "CLIENT"
